//
//  Characters.swift
//  Betrayal stat tracker
//
//  Created by Martin Peshevski on 5.3.21.
//

import UIKit

enum TeamColor {
    case red
    case blue
    case gray
    case purple
    case green
    case yellow
}

struct Character: Equatable {
    let name: String
    let image: UIImage
    let teamColor: TeamColor
    var might: [StatValue]
    var speed: [StatValue]
    var knowledge: [StatValue]
    var sanity: [StatValue]
    
    mutating func setSelected(type: StatType, index: Int) {
        switch type {
        case .might: for (i, _) in might.enumerated() { might[i].isSelected = i == index }
        case .speed: for (i, _) in speed.enumerated() { speed[i].isSelected = i == index }
        case .knowledge: for (i, _) in knowledge.enumerated() { knowledge[i].isSelected = i == index }
        case .sanity: for (i, _) in sanity.enumerated() { sanity[i].isSelected = i == index }
        }
    }
}

let Flash = Character(name: "Darrin \"Flash\" Williams",
                      image: UIImage(named: "Flash") ?? UIImage(),
                      teamColor: .red,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6, isDefault: true),
                         StatValue(value: 7),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 7)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 2),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 7)])

let LongFellow = Character(name: "Professor Longfellow",
                      image: UIImage(named: "Longfellow") ?? UIImage(),
                      teamColor: .gray,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 2),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5, isDefault: true),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7)])

let VivianLopez = Character(name: "Vivian Lopez",
                      image: UIImage(named: "VivianLopez") ?? UIImage(),
                      teamColor: .blue,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 2, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8),
                         StatValue(value: 8)])

let BrandonJaspers = Character(name: "Brandon Jaspers",
                      image: UIImage(named: "BrandonJaspers") ?? UIImage(),
                      teamColor: .green,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)])

let JennyLeClerc = Character(name: "Jenny LeClerc",
                      image: UIImage(named: "JennyLeClerc") ?? UIImage(),
                      teamColor: .purple,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 8)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 8)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 8)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 1),
                         StatValue(value: 2),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6)])

let MissyDubourde = Character(name: "Missy Dubourde",
                      image: UIImage(named: "MissyDubourde") ?? UIImage(),
                      teamColor: .yellow,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 5, isDefault: true),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 7)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 6)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 2),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7)])

let FatherRhinehardt = Character(name: "Father Rhinehardt",
                      image: UIImage(named: "Rhinehardt") ?? UIImage(),
                      teamColor: .gray,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 2),
                         StatValue(value: 2, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 7)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 7)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 8)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6, isDefault: true),
                         StatValue(value: 7),
                         StatValue(value: 7),
                         StatValue(value: 8)])

let MadameZostra = Character(name: "Madame Zostra",
                      image: UIImage(named: "MadameZostra") ?? UIImage(),
                      teamColor: .blue,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8),
                         StatValue(value: 8)])

let ZoeIngstrom = Character(name: "Zoe Ingstrom",
                      image: UIImage(named: "ZoeIngstrom") ?? UIImage(),
                      teamColor: .yellow,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 6),
                         StatValue(value: 7)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 8),
                         StatValue(value: 8)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 1),
                         StatValue(value: 2),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 5)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 5, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)])

let HeatherGranville = Character(name: "Heather Granville",
                      image: UIImage(named: "HeatherGranville") ?? UIImage(),
                      teamColor: .purple,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 5, isDefault: true),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 6)])

let PeterAkimoto = Character(name: "Peter Akimoto",
                      image: UIImage(named: "PeterAkimoto") ?? UIImage(),
                      teamColor: .green,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 8)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 3),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 7)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 7),
                         StatValue(value: 8)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 3),
                         StatValue(value: 4),
                         StatValue(value: 4),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7)])

let OxBellows = Character(name: "Ox Bellows",
                      image: UIImage(named: "OxBellows") ?? UIImage(),
                      teamColor: .red,
                      might:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5, isDefault: true),
                         StatValue(value: 6),
                         StatValue(value: 6),
                         StatValue(value: 7),
                         StatValue(value: 8),
                         StatValue(value: 8)],
                      speed:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 3),
                         StatValue(value: 4, isDefault: true),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6)],
                      knowledge:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 3),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 6)],
                      sanity:
                        [StatValue(value: 0, isDeath: true),
                         StatValue(value: 2),
                         StatValue(value: 2),
                         StatValue(value: 3, isDefault: true),
                         StatValue(value: 4),
                         StatValue(value: 5),
                         StatValue(value: 5),
                         StatValue(value: 6),
                         StatValue(value: 7)])
